#define CONTROL_CAPTURE_MS 5000
#define CONTROL_ACTIONS 11
#define CONTROL_PROFILES 16
typedef struct {unsigned id;int external;char name[80];int code[CONTROL_ACTIONS];unsigned char available[544];} ControlProfile;
static ControlProfile controllers[CONTROL_PROFILES];static int controller_count=1,controller_selected,capture_action=-1,capture_profile;
static uint64_t capture_until;
static const int control_actions[]={ACCEPT,BACK,VIEW,FAV,RECENT,PGUP,PGDN,START,HISTORY,FAVOURITES,MENU};
static const char*control_names[]={"Accept","Back","Search / help","Favourite","View / source","Previous tab","Next tab","Launch mode","Recents","Favourites","Settings"};
static const int handheld_codes[]={304,305,307,306,310,308,309,311,314,315,312};
static const int external_codes[]={304,305,307,308,314,310,311,315,312,313,316};
static int bindable(int c){return c>=256&&c<=543&&c!=354;}
static void controller_defaults(int n){ControlProfile*p=&controllers[n];memcpy(p->code,p->external?external_codes:handheld_codes,sizeof p->code);int known=0;for(int c=256;c<544;c++)known|=p->available[c];if(p->external&&known){for(int i=0;i<CONTROL_ACTIONS;i++){int code=external_codes[i],used=0;for(int j=0;j<i;j++)if(p->code[j]==code)used=1;if(!p->available[code]||used){code=0;for(int c=256;c<544;c++)if(p->available[c]&&bindable(c)){int taken=0;for(int j=0;j<i;j++)if(p->code[j]==c)taken=1;if(!taken){code=c;break;}}if(!code)for(int c=256;c<544;c++)if(bindable(c)){int taken=0;for(int j=0;j<i;j++)if(p->code[j]==c)taken=1;if(!taken){code=c;break;}}}p->code[i]=code;}}}
static int controller_valid(ControlProfile*p){for(int i=0;i<CONTROL_ACTIONS;i++){if(!bindable(p->code[i]))return 0;for(int j=0;j<i;j++)if(p->code[j]==p->code[i])return 0;}return 1;}
static void controller_save(void){char path[PATHLEN],data[6000];size_t len=0;statepath(path,"controllers.txt");for(int n=0;n<controller_count;n++){ControlProfile*p=&controllers[n];len+=snprintf(data+len,sizeof data-len,"%u %d",p->id,p->external);for(int i=0;i<CONTROL_ACTIONS;i++)len+=snprintf(data+len,sizeof data-len," %d",p->code[i]);len+=snprintf(data+len,sizeof data-len,"\n");}atomic_text(path,data);}
static void controller_load(void){memset(controllers,0,sizeof controllers);controller_count=1;strcpy(controllers[0].name,"RG SP");controller_defaults(0);char path[PATHLEN],line[512];statepath(path,"controllers.txt");FILE*f=fopen(path,"r");if(!f)return;while(fgets(line,sizeof line,f)){ControlProfile p={0};int used=0;if(sscanf(line,"%u %d%n",&p.id,&p.external,&used)!=2||p.external<0||p.external>1)continue;char*q=line+used;int ok=1;for(int i=0;i<CONTROL_ACTIONS;i++){if(sscanf(q," %d%n",&p.code[i],&used)!=1){ok=0;break;}q+=used;}if(!ok||!controller_valid(&p))continue;int n=p.id?controller_count:0;if(n>=CONTROL_PROFILES)break;if(p.id)controller_count++;controllers[n]=p;snprintf(controllers[n].name,sizeof p.name,p.id?"Controller %d":"RG SP",n);}fclose(f);}
static void controller_bind(int profile,int action,int code){ControlProfile*p=&controllers[profile];if(!bindable(code)||action<0||action>=CONTROL_ACTIONS)return;int old=p->code[action];for(int i=0;i<CONTROL_ACTIONS;i++)if(p->code[i]==code)p->code[i]=old;p->code[action]=code;controller_save();extra_revision++;}
static int controller_key(int profile,int code){if(code==103||code==544)return UP;if(code==108||code==545)return DOWN;if(code==105||code==546)return LEFT;if(code==106||code==547)return RIGHT;for(int i=0;i<CONTROL_ACTIONS;i++)if(controllers[profile].code[i]==code)return control_actions[i];return 0;}
static const char*control_label(int action){static char buf[8][20];static unsigned slot;char*out=buf[(slot++)%8];int index=-1;for(int i=0;i<CONTROL_ACTIONS;i++)if(control_actions[i]==action)index=i;if(index<0)return "D-pad";ControlProfile*p=&controllers[controller_selected];int code=p->code[index];const char*name=NULL;
 if(!p->external){for(int i=0;i<CONTROL_ACTIONS;i++)if(handheld_codes[i]==code){static const char*names[]={"A","B","X","Y","SELECT","L","R","START","L2","R2","MENU"};name=names[i];}}
 else switch(code){case 304:name="South";break;case 305:name="East";break;case 307:name="North";break;case 308:name="West";break;case 310:name="L";break;case 311:name="R";break;case 312:name="L2";break;case 313:name="R2";break;case 314:name="Select";break;case 315:name="Start";break;case 316:name="Guide";break;}
 if(name)snprintf(out,20,"%s",name);else snprintf(out,20,"Button %d",code);return out;}
